<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-EAD491B" failures="1" tests="11" name="Default test" time="0.394" errors="0" timestamp="2022-10-10T18:13:01 IST">
  <testcase classname="Demo1.TestNg3" name="ModifyCustomer" time="0.014"/>
  <testcase classname="Demo1.TestNg3" name="createCustomer" time="0.009"/>
  <testcase classname="Demo1.TestNg3" name="editCustomer" time="0.046">
    <failure type="java.lang.AssertionError" message="expected [ABC] but found [ABCD]">
      <![CDATA[java.lang.AssertionError: expected [ABC] but found [ABCD]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Demo1.TestNg3.editCustomer(TestNg3.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- editCustomer -->
  <testcase classname="Demo1.TestNg3" name="deleteCustomer" time="0.003">
    <skipped/>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="Demo1.TestNg" name="CreateReport" time="0.005"/>
  <testcase classname="Demo1.TestNg1" name="createCustomer" time="0.005"/>
  <testcase classname="Demo1.TestNg1" name="deleteCustomer" time="0.009"/>
  <testcase classname="Demo1.TestNg1" name="editCustomer" time="0.003"/>
  <testcase classname="Demo1.TestNg2" name="createCustomer" time="0.002"/>
  <testcase classname="Demo1.TestNg2" name="editCustomer" time="0.012"/>
  <testcase classname="Demo1.TestNg2" name="deleteCustomer" time="0.002"/>
  <testcase classname="Demo1.TestNg2" name="ModifyCustomer" time="0.0">
    <ignored/>
  </testcase> <!-- ModifyCustomer -->
</testsuite> <!-- Default test -->
